### ISSUE TITLE
Analysis

### ISSUE THREAD

**Issue by PanosEconomou** [nyuad-astroparticle/apxs#8]
Perform Analysis of simulation data in python

- [x] Create a python notebook to perform analysis
- [x] Parallelize it
- [x] Convert everything to scripts
- [x] hopefully automatize it

**Comment by PanosEconomou** [comment]
Created a parallel analysis script in e62dc6769b1ca8d99aecbb1ea0443c79a98c3c79

**Comment by PanosEconomou** [comment]
It is automatized as of a3faaf49baf090a1f1f1f9b57974e531620358e5

**Comment by F7East** [comment]
Can't convert everything to scripts because we want the sources to be too flexible( 
I tried tho ..
